//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scafolding
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materias
    {
        public Materias()
        {
            this.Grupos = new HashSet<Grupos>();
        }
    
        public string Clave { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Grupos> Grupos { get; set; }
    }
}
